package certification.oracle;

//===============
//public class ExceptionClass {
//public static void main(String args[]) {
//	FileInputStream fis = null;
//try {
//      fis = new FileInputStream("file.txt");
//      System.out.println("File Opened");
//      fis.read();
//      System.out.println("Read File");
//} 
//finally {
//
//	 System.out.println("finally");
// 
//
//} catch (FileNotFoundException fnfe){ 
//	System.out.println("File not found");
//} 
//catch (IOException ioe) {
//	System.out.println("File Closing Exception");
//}
//System.out.println("Next task..");
//}
//}
//=========================

class FallInRiverException extends Exception {
}

class RiverRafting {

	void crossRapid(int degree) throws FallInRiverException {
		System.out.println("Cross Rapid");
		if (degree > 10)
			throw new FallInRiverException();
	}
}

class ExceptionClass {
	public static void main(String args[]) {
		RiverRafting riverRafting = new RiverRafting();
		riverRafting.crossRapid(9);
	}
}
// main is not throwing any exception or neither handling
==================